;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	))

(setq mc/cmds-to-run-once
      '(
	cua-paste
	find-file
	mouse-minor-mode-menu
	mouse-select-window
	mouse-set-region
	python-indent-electric-colon
	write-file
	))
